import Head from 'next/head'
import styles from '../styles/Homepage.module.css'
import 'bulma/css/bulma.css'
import Link from 'next/link'

const Homepage = () => {
    return(
        //outside container
        <div className={styles.main}>
            
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <nav className='navbar is-primary is-fixed-top'> 
                <div className='container'>
                    <div className='navbar-brand'>
                        <div className='navbar-item'>
                            <Link href='/homepage'>
                                <a>Home</a>
                            </Link>
                        </div>

                    </div>
                    
                    <div className='navbar-end'> 
                        <div className='navbar-item'>
                            <div class="field is-grouped">
                                <Link href='/application'>
                                    <a>Enter app</a>
                                </Link>
                            </div>
                        </div>
                    </div>
                    

                    <div className='navbar-end'>

                    </div>
                </div>
            </nav>

            <div className={styles.main}>
                

                <div> /*1st row*/

                </div>
                <div> /*2nd row*/

                </div>
                <div> /*3rd row*/

                </div>
            
            </div>
            <footer>

            </footer>
            
        </div>
        
    )

}

export default Homepage