import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Cases.module.css'

const Cases = () => {
    return(
        <div className={styles.main}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <nav className="navbar is-primary is-fixed-top has-background-black-bis">
                <div className="navbar-menu">
                    <div className="container">
                        <div className="navbar-brand">
                        <div className='navbar-item'></div>
                        <div className='navbar-item'></div>
                        <div className='navbar-item'></div>
                        <div className='navbar-item'></div>
                            <div className='navbar-item'>
                                <Link href='/'>
                                    <a><h1>A web app</h1></a>
                                </Link>
                            </div> 
                        </div>
                    </div> 
                </div>
                
                <div className="navbar-end">
                    <div className='navbar-item'>
                        <Link href='/why'>
                            <a>Why</a>
                        </Link>
                    </div>
                </div>
                <div className="navbar-end">
                    <div className='navbar-item'>
                        <Link href='/Use cases'>
                            <a>Use cases</a>
                        </Link>
                    </div>
                </div>
                <div className="navbar-end">
                    <div className='navbar-item'>
                        <Link href='/how-it-works'>
                            <a>How it works</a>
                        </Link>
                    </div>
                </div>
                <div className="navbar-end">
                    <div className='navbar-item'>
                        <Link href='/deployed-features'>
                            <a>Features</a>
                        </Link>
                    </div>
                </div>
                <div className="navbar-end">
                    <div className='navbar-item'>
                        <Link href='/statistic'>
                            <a>Statistic</a>
                        </Link>
                    </div>
                </div>
                <div className="navbar-end">
                    <div className='navbar-item'>
                        <Link href='/community'>
                            <a>Community</a>
                        </Link>
                    </div>
                </div>
                <div className="navbar-end">
                    <div className='navbar-item'>
                        <Link href='/application'>
                            <a>Enter app</a>
                        </Link>
                    </div>
                    <div className='navbar-item'>
                    </div>
                </div>
            </nav>

            <section id='first' className="hero is-medium has-background-black-bis">
                <div className="hero-body">
                  <div className="container has-text-centered">
                    <text className="title">
                    Legal agreements
                    </text>
                    <p className="has-text-left pb-6 pt-4 pl-5 mt-5">
                        <h2>The purpose</h2>
                        Enabling people to have access to creation of legal agreements with other subjects in their community or worldwide.

                        <h2 >How to achieve the above?</h2>
                        By using smart contracts, we make sure that subjects who don't know eachother and 
                        don't have physical access to one another, fulfill their obligations to eachother 
                        without cheating the system.

                        <h2 >What kind of legal agreements will be implemented?</h2>
                        We will ask our community to help us find the most usefull legal agreements for them.

                        <h2 >When will these features be implemented?</h2>
                        We can't provide any exact date. However, we are trying to provide it as soon as possible.

                        <h2 >Which blockchains will be used to deploy the smart contracts?</h2>
                        Firstly, the smart contracts will be deployed on the Ethereum mainnet. 
                        After some time we will deploy them to other Ethereum L2 scaling solutions.  
                        We haven't yet decided which scalin solutions will be used.  

                        <h2 >How much commission will we charge?</h2>
                        A feature in the smart contract lets us to change the commission from 1 to 10**15 weis. 
                        This enables us to respond to rapid changes in supply and demand of our system and other events in the world.
                        The exact commission amount can be checked for a specific smart contract.
                    </p>
                  </div>
                </div>
            </section>

            <section id='second' className="hero is-medium has-background-black-bis">
                <div className="hero-body">
                  <div className="container has-text-centered">
                    <text className="title mb-6">
                    Financial commitments
                    </text>
                    <p className="has-text-left pb-6 pt-4 pl-5 mt-5">
                        <h2>The purpose</h2>
                        Enabling people to create financial agreements with other subjects all over the world.

                        <h2 >How to achieve the above?</h2>
                        By using smart contracts, we make sure that subjects who don't know eachother and 
                        don't have physical access to one another, fulfill their obligations to eachother 
                        without cheating the system.

                        <h2 >What kind of financial agreements will be implemented?</h2>
                        Enabling person A to commit sending payment every X amount to person B every Y time period for the duration of Z time starting at Q.<br></br>
                        Enabling person A to commit sending a payment till T.<br></br>
                        Also, we are open to any suggestions fromour community.<br></br>

                        <h2 >When will these features be implemented?</h2>
                        We have already deployed a smart contract enabling person A to commit sending payment 
                        every X amount to person B every Y time period for the duration of Z time starting at Q.
                        In the short future we will deploy a smart contract that will enable subjects to commit sending a payment till T.

                        <h2 >Which blockchains will be used to deploy the smart contracts?</h2>
                        Firstly, the smart contracts will be deployed on the Ethereum mainnet. 
                        After some time we will deploy them to other Ethereum L2 scaling solutions.  
                        We haven't yet decided which scalin solutions will be used.

                        <h2 >How much commission do we charge?</h2>
                        A feature in the smart contract lets us to change the commission from 1 to 10**15 weis. 
                        This enables us to respond to rapid changes in supply and demand of our system and other events in the world.
                        The exact commission amount can be checked for a specific smart contract.
                    </p>
                  </div>
                </div>
            </section>

            <section id='third' className="hero is-medium has-background-black-bis">
                <div className="hero-body">
                  <div className="container has-text-centered">
                    <text className="title mb-6">
                    Token vault
                    </text>
                    <p className="has-text-left pb-6 pt-4 pl-5 mt-5">
                        <h2>The purpose</h2>
                        Enabling people to not get emotional in the bear markets and sell ethers.
                        
                        <h2>How to achieve the above?</h2>
                        The user can send ethers to the smart contract and specifies from which date onwards can the ethers be withdrawn.

                        <h2>Which tokens can be locked in this vault?</h2>
                        Currently, only ethers. We will discuss pros ans cons of creating a vault for other tokens and see if this would be a beneficial project. 

                        <h2 >When will these features be implemented?</h2>
                        The vault for locking ether is already implemented.

                        <h2 >Which blockchains will be used to deploy the smart contracts?</h2>
                        Firstly, the smart contracts will be deployed on the Ethereum mainnet. 
                        After some time we will deploy them to other Ethereum L2 scaling solutions.  
                        We haven't yet decided which scalin solutions will be used.

                        <h2 >How much commission do we charge?</h2>
                        Nothing, it's free for using.
                    </p>
                  </div>
                </div>
            </section>

        </div>
        
    )
}

export default Cases