import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Why.module.css'

const Why = () => {
    return(
        <div className={styles.main}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>Why</h1>

            <nav className="navbar is-primary is-fixed-top">
                <div className="navbar-menu">
                    <div className="container">
                        <div className="navbar-brand">
                        <div className='navbar-item'>
                            <Link href='/'>
                                <a><h1>A web app</h1></a>
                            </Link>
                        </div> 
                        </div>
                    </div> 
                </div>
                
                <div className="navbar-end">
                    <div className='navbar-item'>
                            <Link href='/why'>
                                <a>Why</a>
                            </Link>
                        </div>
                    </div>
                    <div className="navbar-end">
                    <div className='navbar-item'>
                            <Link href='/how-it-works'>
                                <a>How it works</a>
                            </Link>
                        </div>
                    </div>
                    <div className="navbar-end">
                    <div className='navbar-item'>
                        <Link href='/application'>
                            <a>Enter app</a>
                        </Link>
                    </div>
                    <div className='navbar-item'>
                    </div>
                </div>
            </nav>

        </div>
        
    )
}

export default Why